# Generated by Django 5.1.2 on 2025-10-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='reading',
            name='humidity',
            field=models.DecimalField(decimal_places=2, help_text='Humidity percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reading',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
